# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: backup0
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v.1.0.15-d596bde"
  os: linux
  arch: amd64
secret:
  name: buddybot
  tokenKey: token
  tokenName: TELE_TOKEN
